export enum TipoOperacionFactura {
  COMPRA = 'COMPRA',
  VENTA = 'VENTA',
  INTERNA = 'INTERNA',
  IMPORTACION = 'IMPORTACION',
  EXPORTACION = 'EXPORTACION',
  TRANSFERENCIA = 'TRANSFERENCIA',
  NOTA_CREDITO = 'NOTA_CREDITO',
  NOTA_DEBITO = 'NOTA_DEBITO'
}
