export enum TipoEstiloCuenta{
    RAZONSIMPLES = "RAZONSIMPLES",
    BANCO = "BANCO",
    CUENTAACOBRARPAGAR = "CUENTAACOBRARPAGAR",
    CUENTACORRIENTE = "CUENTACORRIENTE",
    EXISTENCIA = "EXISTENCIA",
    CUENTADEBIENES = "CUENTADEBIENES",
    CONTRACTOS = "CONTRACTOS",
    CARTERADECHEQUESRECIBIDOS = "CARTERADECHEQUESRECIBIDOS",
    NINGUN = "NINGUN"
}