export enum TipoCondicionVenta {
    ALCONTADOEFECTIVO = 'ALCONTADOEFECTIVO',
    ALCONTADOCHEQUE  = 'ALCONTADOCHEQUE',
    ALCONTADOCTACORRIENTE = 'ALCONTADOCTACORRIENTE',
    ACREDITO = 'ACREDITO',
    DONACIONES = 'DONACIONES',
    PROMOCIONES = 'PROMOCIONES'
}