export enum TipoSituacion {
  ACTIVO = "ACTIVO",
  INACTIVO = "INACTIVO",
  EVALUANDO = "EVALUANDO",
  BLOQUEADO = "BLOQUEADO",
  ABIERTA = 'ABIERTA',
  CANCELADA = 'CANCELADA',
  CERRADA = 'CERRADA',
  TRANSFERENCIA = 'TRANSFERENCIA'
}
