export enum TipoRuc {
  COMERCIAL = "COMERCIAL",
  SERVICIO = "SERVICIO",
  COMERCIALSERVICIO = "COMERCIAL_SERVICIO",
  IMAGRO = "IMAGRO",
  COMERCIALIMAGRO = "COMERCIAL_IMAGRO",
  SERVICIOIMAGRO = "SERVICIO_IMAGRO",
  SERVICIOCOMERCIALIMAGRO = "SERVICIO_COMERCIAL_IMAGRO"
}
